const nodemailer = require('nodemailer');
const axios = require('axios');
const logger = require('../utils/logger');
const { frontendUrl } = require('../config/urls');

/**
 * Escape a value being interpolated into an HTML email body.
 *
 * These templates are built by string concatenation, so anything interpolated is
 * markup until proven otherwise. The verification code is generated by us from
 * digits only and needs nothing escaped, but a template that relies on that
 * staying true is one refactor away from an injection point — and the escaping is
 * three lines.
 *
 * Not a general-purpose sanitiser: it covers the five characters that can break
 * out of an HTML text node or attribute value, which is all these bodies use.
 */
function escapeHtml(value) {
  return String(value)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}

const NAMED_ENTITIES = {
  nbsp: ' ', amp: '&', lt: '<', gt: '>', quot: '"', apos: "'",
  eacute: 'é', egrave: 'è', agrave: 'à', ccedil: 'ç', ugrave: 'ù', ocirc: 'ô'
};

/**
 * Resolve HTML entities in a stored value.
 *
 * Necessary because stored values are inconsistent: the scraper's `clean()` only
 * decodes `&nbsp;`, while its other source uses cheerio's `.text()`, which decodes
 * everything. So a company stored as "Acme &amp; Sons" is a real value.
 *
 * Numeric references are resolved too, and that is safe in both directions because
 * every caller either escapes (for HTML) or strips tags (for text) afterwards: a
 * stored "&#60;script&#62;" cannot reach a reader as a live tag.
 */
function decodeEntities(value) {
  return String(value == null ? '' : value).replace(
    /&(#x[0-9a-f]+|#\d+|[a-z]+);/gi,
    (match, body) => {
      const key = body.toLowerCase();
      if (Object.prototype.hasOwnProperty.call(NAMED_ENTITIES, key)) return NAMED_ENTITIES[key];
      if (key[0] === '#') {
        const code = key[1] === 'x' ? parseInt(key.slice(2), 16) : parseInt(key.slice(1), 10);
        if (Number.isFinite(code) && code > 0 && code <= 0x10ffff) return String.fromCodePoint(code);
      }
      return match;
    }
  );
}

/**
 * Reduce a stored value to plain text: resolve entities, strip tags, collapse space.
 *
 * Decode first, then strip. The reverse order leaves a stored "&lt;img src=x&gt;"
 * decoding into a live tag after the strip has already run.
 */
function plainText(value) {
  return decodeEntities(value)
    .replace(/<[^>]*>/g, ' ')
    .replace(/\s+/g, ' ')
    .trim();
}

/**
 * A stored value rendered safely into an HTML body.
 *
 * plainText first, escapeHtml second -- in that order, and only in that order.
 * Escaping alone double-escapes an entity the scraper already decoded, so a company
 * stored as "Acme &amp; Sons" reaches the reader as "Acme &amp;amp; Sons"; stripping
 * alone leaves live markup. Doing both means the HTML part shows the same characters
 * as the text part.
 */
function htmlText(value) {
  return escapeHtml(plainText(value));
}

let transporter = null;

const FROM = process.env.SMTP_FROM || 'CVBoost <noreply@cvboost.app>';

// Brevo's transactional API is reached over HTTPS on port 443, which no cloud
// provider blocks. This matters because Render blocks outbound SMTP (25/465/587)
// on free instances — see the platform changelog — so an SMTP transport there
// fails with a bare "Connection timeout" and no usable diagnostics.
const BREVO_ENDPOINT = 'https://api.brevo.com/v3/smtp/email';

// Nodemailer waits 120s for an SMTP connection by default. Over a blocked port
// that is 120s of silence per email before anything is logged, so keep the
// HTTP path short and let it report a real reason.
const BREVO_TIMEOUT_MS = parseInt(process.env.BREVO_TIMEOUT_MS || '15000', 10);

/**
 * Split `CVBoost <noreply@cvboost.app>` into the shape Brevo expects.
 * Brevo rejects a `sender` it has not verified, so a malformed or unverified
 * FROM must fail loudly rather than silently produce an undeliverable message.
 */
function parseFrom(from) {
  const match = /^\s*(.*?)\s*<([^>]+)>\s*$/.exec(from || '');
  if (match) return { name: match[1] || undefined, email: match[2].trim() };
  return { email: (from || '').trim() };
}

/**
 * Minimal transport with the same `sendMail` contract as a nodemailer
 * transporter, so `sendMail()` below is unaware of which one is in use.
 */
function createBrevoTransport(apiKey) {
  return {
    kind: 'brevo-api',
    async sendMail({ from, to, subject, html, text, attachments }) {
      const payload = {
        sender: parseFrom(from),
        to: [{ email: to }],
        subject,
        htmlContent: html,
        textContent: text
      };

      // Brevo takes attachments as { name, content } with base64 content.
      if (attachments && attachments.length) {
        payload.attachment = attachments.map((a) => ({
          name: a.filename,
          content: Buffer.isBuffer(a.content) ? a.content.toString('base64') : a.content
        }));
      }

      const response = await axios.post(BREVO_ENDPOINT, payload, {
        timeout: BREVO_TIMEOUT_MS,
        headers: {
          'api-key': apiKey,
          'content-type': 'application/json',
          accept: 'application/json'
        }
      });

      // Brevo answers 201 with the message id in a header, not the body.
      return {
        messageId: response.headers?.['x-message-id'] || response.data?.messageId || 'unknown'
      };
    }
  };
}

function getTransporter() {
  if (transporter) return transporter;

  const { SMTP_HOST, SMTP_PORT, SMTP_USER, SMTP_PASS, SMTP_FROM, BREVO_API_KEY } = process.env;

  // Prefer the HTTPS API: it works on every host, including platforms that
  // block outbound SMTP. This is the path a Render free instance must take.
  if (BREVO_API_KEY) {
    if (!SMTP_FROM) {
      logger.warn('BREVO_API_KEY is set but SMTP_FROM is not — Brevo will reject an unverified sender');
    }
    transporter = createBrevoTransport(BREVO_API_KEY);
    logger.info('Email transport: Brevo API over HTTPS (port 443)');
    return transporter;
  }

  if (!SMTP_HOST) {
    logger.warn('No BREVO_API_KEY and no SMTP_HOST — emails will be logged to console only');
    return null;
  }

  if (!SMTP_USER || !SMTP_PASS) {
    logger.warn('SMTP host set but no credentials — emails will be logged to console only');
    return null;
  }

  logger.info(`Email transport: SMTP ${SMTP_HOST}:${SMTP_PORT || '587'}`);
  transporter = nodemailer.createTransport({
    host: SMTP_HOST,
    port: parseInt(SMTP_PORT || '587', 10),
    secure: parseInt(SMTP_PORT || '587', 10) === 465,
    auth: { user: SMTP_USER, pass: SMTP_PASS }
  });

  return transporter;
}

async function sendMail({ to, subject, html, text, attachments }) {
  const transport = getTransporter();

  if (!transport) {
    logger.info(`[EMAIL — console only] To: ${to} | Subject: ${subject} | Attachments: ${(attachments || []).map(a => a.filename).join(', ') || 'none'}`);
    logger.info(`[EMAIL body] ${text || html}`);
    return { success: true, consoleOnly: true };
  }

  try {
    const info = await transport.sendMail({ from: FROM, to, subject, html, text, attachments });
    logger.info(`Email sent to ${to}: ${info.messageId}`);
    return { success: true, messageId: info.messageId };
  } catch (err) {
    // Distinguish the failure modes an operator actually has to act on. A bare
    // "Connection timeout" tells you nothing about which of these it is.
    let reason = err.message;
    if (transport.kind === 'brevo-api' && err.response) {
      const status = err.response.status;
      const apiMessage = err.response.data?.message;
      if (status === 401 || status === 403) {
        reason = `Brevo rejected the API key (${status}) — check BREVO_API_KEY`;
      } else if (status === 400 && /sender/i.test(apiMessage || '')) {
        reason = `Brevo rejected the sender "${FROM}" (${apiMessage}) — verify this address in Brevo, then set SMTP_FROM to match`;
      } else if (status === 429) {
        reason = 'Brevo rate limit reached';
      } else if (apiMessage) {
        reason = `Brevo ${status}: ${apiMessage}`;
      }
    } else if (transport.kind !== 'brevo-api' && /timeout|ETIMEDOUT|ENETUNREACH|EAI_AGAIN/i.test(reason)) {
      reason += ' — the host may block outbound SMTP (ports 25/465/587); set BREVO_API_KEY to send over HTTPS instead';
    }
    logger.error(`Email failed to ${to}: ${reason}`);
    return { success: false, error: reason };
  }
}

async function sendPasswordResetEmail(email, token, language = 'en') {
  const baseUrl = frontendUrl();
  const resetUrl = `${baseUrl}/reset-password?token=${token}`;

  const subjects = {
    en: 'Reset Your CVBoost Password',
    fr: 'Réinitialisez votre mot de passe CVBoost'
  };

  const bodies = {
    en: `
      <div style="font-family:system-ui,sans-serif;max-width:480px;margin:0 auto;padding:32px;">
        <h2 style="color:#4f46e5;">Reset Your Password</h2>
        <p>You requested a password reset for your CVBoost account.</p>
        <p>Click the button below to set a new password. This link expires in 1 hour.</p>
        <a href="${resetUrl}" style="display:inline-block;background:#4f46e5;color:#fff;padding:12px 24px;border-radius:8px;text-decoration:none;font-weight:600;margin:16px 0;">Reset Password</a>
        <p style="color:#64748b;font-size:13px;">If you didn't request this, you can safely ignore this email.</p>
        <hr style="border:none;border-top:1px solid #e2e8f0;margin:24px 0;" />
        <p style="color:#94a3b8;font-size:12px;">CVBoost — Tailor your CV with AI</p>
      </div>
    `,
    fr: `
      <div style="font-family:system-ui,sans-serif;max-width:480px;margin:0 auto;padding:32px;">
        <h2 style="color:#4f46e5;">Réinitialisez votre mot de passe</h2>
        <p>Vous avez demandé la réinitialisation du mot de passe de votre compte CVBoost.</p>
        <p>Cliquez sur le bouton ci-dessous pour définir un nouveau mot de passe. Ce lien expire dans 1 heure.</p>
        <a href="${resetUrl}" style="display:inline-block;background:#4f46e5;color:#fff;padding:12px 24px;border-radius:8px;text-decoration:none;font-weight:600;margin:16px 0;">Réinitialiser</a>
        <p style="color:#64748b;font-size:13px;">Si vous n'avez pas fait cette demande, vous pouvez ignorer cet email.</p>
        <hr style="border:none;border-top:1px solid #e2e8f0;margin:24px 0;" />
        <p style="color:#94a3b8;font-size:12px;">CVBoost — Adaptez votre CV avec l'IA</p>
      </div>
    `
  };

  return sendMail({
    to: email,
    subject: subjects[language] || subjects.en,
    html: bodies[language] || bodies.en,
    text: `Reset your CVBoost password: ${resetUrl}`
  });
}

// Rendered large and letter-spaced on purpose: six digits are easy to mistype
// when read off a screen, and a wrong guess costs one of five attempts.
//
// `letter-spacing` plus a fallback font stack is the compromise for keeping them
// legible in clients that strip `font-family`, and `word-break:break-all` stops a
// client that ignores letter-spacing from wrapping the code mid-number on a
// narrow mobile viewport.
//
// The code is passed through the same HTML escaping as the rest of the template.
// It is generated by us from digits only, so there is nothing to escape in
// practice — but a template that interpolates a value into markup should not
// depend on that staying true, and the escaping is already imported here.
function verificationCodeBlock(code) {
  if (!code) return '';
  return `
    <div style="background:#f8fafc;border:2px solid #e2e8f0;border-radius:12px;padding:24px 16px;margin:24px 0;text-align:center;">
      <div style="font-size:13px;color:#64748b;text-transform:uppercase;letter-spacing:1px;margin-bottom:12px;">${escapeHtml(String(code).slice(0, 16))}</div>
      <div style="font-family:ui-monospace,SFMono-Regular,Menlo,monospace;font-size:36px;font-weight:700;letter-spacing:10px;color:#0f172a;word-break:break-all;line-height:1.2;">${escapeHtml(String(code).slice(0, 16))}</div>
    </div>
  `;
}

async function sendVerificationEmail({ email, token, code, language = 'en' }) {
  const baseUrl = frontendUrl();
  const verifyUrl = `${baseUrl}/verify-email?token=${token}`;

  const subjects = {
    en: 'Verify your CVBoost email',
    fr: 'Vérifiez votre email CVBoost'
  };

  // The link and the code are both always offered, for the same reason GitHub
  // offers both: the link works on a phone with no way to retype digits, and the
  // code works on a desktop where clicking a link would abandon whatever the user
  // was doing. A user who has neither the inbox to hand nor a comfortable way to
  // switch devices can still get through.
  //
  // The code is rendered unconditionally so both language variants of the template
  // stay structurally identical — a branch here would be one more place for the
  // two to drift.
  const bodies = {
    en: `
      <div style="font-family:system-ui,sans-serif;max-width:480px;margin:0 auto;padding:32px;">
        <h2 style="color:#4f46e5;">Welcome to CVBoost!</h2>
        <p>You're almost there. Confirm your email address to finish setting up your account.</p>
        <p style="margin:20px 0 0;color:#334155;font-size:15px;font-weight:600;">Enter this code on the verification page:</p>
        ${verificationCodeBlock(code)}
        <p style="color:#64748b;font-size:13px;">The code expires in 10 minutes. You have 5 attempts.</p>
        <p style="color:#334155;font-size:15px;font-weight:600;margin:24px 0 8px;">Or verify with one click:</p>
        <a href="${verifyUrl}" style="display:inline-block;background:#4f46e5;color:#fff;padding:12px 24px;border-radius:8px;text-decoration:none;font-weight:600;">Verify Email</a>
        <p style="color:#64748b;font-size:13px;">This link expires in 24 hours.</p>
        <p style="color:#64748b;font-size:13px;">If you didn't create a CVBoost account, you can safely ignore this email.</p>
        <hr style="border:none;border-top:1px solid #e2e8f0;margin:24px 0;" />
        <p style="color:#94a3b8;font-size:12px;">CVBoost — Tailor your CV with AI</p>
      </div>
    `,
    fr: `
      <div style="font-family:system-ui,sans-serif;max-width:480px;margin:0 auto;padding:32px;">
        <h2 style="color:#4f46e5;">Bienvenue sur CVBoost !</h2>
        <p>Vous y êtes presque. Confirmez votre adresse email pour finaliser la création de votre compte.</p>
        <p style="margin:20px 0 0;color:#334155;font-size:15px;font-weight:600;">Saisissez ce code sur la page de vérification :</p>
        ${verificationCodeBlock(code)}
        <p style="color:#64748b;font-size:13px;">Le code expire dans 10 minutes. Vous avez 5 tentatives.</p>
        <p style="color:#334155;font-size:15px;font-weight:600;margin:24px 0 8px;">Ou vérifiez en un clic :</p>
        <a href="${verifyUrl}" style="display:inline-block;background:#4f46e5;color:#fff;padding:12px 24px;border-radius:8px;text-decoration:none;font-weight:600;">Vérifier l'email</a>
        <p style="color:#64748b;font-size:13px;">Ce lien expire dans 24 heures.</p>
        <p style="color:#64748b;font-size:13px;">Si vous n'avez pas créé de compte CVBoost, vous pouvez ignorer cet email.</p>
        <hr style="border:none;border-top:1px solid #e2e8f0;margin:24px 0;" />
        <p style="color:#94a3b8;font-size:12px;">CVBoost — Adaptez votre CV avec l'IA</p>
      </div>
    `
  };

  // The plain-text alternative carries the code too. Plenty of users read mail in
  // a client that renders text, and a code that only exists in the HTML part is
  // invisible to them — they would find the link and never know a code was sent.
  const text = code
    ? [
      'Welcome to CVBoost!',
      '',
      `Your verification code: ${code}`,
      'It expires in 10 minutes and you have 5 attempts.',
      '',
      `Or verify with one click: ${verifyUrl}`,
      'This link expires in 24 hours.',
      '',
      "If you didn't create a CVBoost account, you can safely ignore this email."
    ].join('\n')
    : `Welcome to CVBoost! Verify your email: ${verifyUrl}`;

  return sendMail({
    to: email,
    subject: subjects[language] || subjects.en,
    html: bodies[language] || bodies.en,
    text
  });
}

async function sendPaymentReceiptEmail({ email, amount, currency = 'XAF', type = 'one-time', reference, provider, date, language = 'en', attachments }) {
  const providerLabel = provider === 'orange' ? 'Orange Money' : 'MTN MoMo';
  const typeLabel = type === 'subscription' ? 'Monthly subscription' : 'CV download';
  const typeLabelFr = type === 'subscription' ? 'Abonnement mensuel' : 'Téléchargement de CV';
  const formattedDate = date ? new Date(date).toLocaleString(language === 'fr' ? 'fr-CM' : 'en-GB') : '';

  const subjects = {
    en: `Payment confirmed — ${typeLabel}`,
    fr: `Paiement confirmé — ${typeLabelFr}`
  };

  const bodies = {
    en: `
      <div style="font-family:system-ui,sans-serif;max-width:480px;margin:0 auto;padding:32px;">
        <h2 style="color:#4f46e5;">Payment confirmed!</h2>
        <p>Thank you! Your payment was successful. Here are the details:</p>
        <div style="background:#f8fafc;border:1px solid #e2e8f0;border-radius:8px;padding:16px;margin:16px 0;">
          <p style="margin:0 0 6px;"><strong>Item:</strong> ${typeLabel}</p>
          <p style="margin:0 0 6px;"><strong>Amount:</strong> ${amount.toLocaleString('en-US')} ${currency}</p>
          <p style="margin:0 0 6px;"><strong>Paid via:</strong> ${providerLabel}</p>
          <p style="margin:0 0 6px;"><strong>Reference:</strong> ${reference}</p>
          ${formattedDate ? `<p style="margin:0;"><strong>Date:</strong> ${formattedDate}</p>` : ''}
        </div>
        <p>You can now continue on CVBoost.</p>
        <hr style="border:none;border-top:1px solid #e2e8f0;margin:24px 0;" />
        <p style="color:#94a3b8;font-size:12px;">CVBoost — Tailor your CV with AI</p>
      </div>
    `,
    fr: `
      <div style="font-family:system-ui,sans-serif;max-width:480px;margin:0 auto;padding:32px;">
        <h2 style="color:#4f46e5;">Paiement confirmé !</h2>
        <p>Merci ! Votre paiement a été effectué avec succès. Voici les détails :</p>
        <div style="background:#f8fafc;border:1px solid #e2e8f0;border-radius:8px;padding:16px;margin:16px 0;">
          <p style="margin:0 0 6px;"><strong>Article :</strong> ${typeLabelFr}</p>
          <p style="margin:0 0 6px;"><strong>Montant :</strong> ${amount.toLocaleString('fr-FR')} ${currency}</p>
          <p style="margin:0 0 6px;"><strong>Paiement via :</strong> ${providerLabel}</p>
          <p style="margin:0 0 6px;"><strong>Référence :</strong> ${reference}</p>
          ${formattedDate ? `<p style="margin:0;"><strong>Date :</strong> ${formattedDate}</p>` : ''}
        </div>
        <p>Vous pouvez maintenant continuer sur CVBoost.</p>
        <hr style="border:none;border-top:1px solid #e2e8f0;margin:24px 0;" />
        <p style="color:#94a3b8;font-size:12px;">CVBoost — Adaptez votre CV avec l'IA</p>
      </div>
    `
  };

  const attachmentNote = attachments && attachments.length > 0
    ? (language === 'fr'
        ? '<p style="color:#334155;font-weight:600;">Vos documents (CV et lettre de motivation) sont joints à cet email.</p>'
        : '<p style="color:#334155;font-weight:600;">Your documents (CV and cover letter) are attached to this email.</p>')
    : '';
  const htmlBody = (bodies[language] || bodies.en).replace(
    '<hr style="border:none;border-top:1px solid #e2e8f0;margin:24px 0;" />',
    `${attachmentNote}<hr style="border:none;border-top:1px solid #e2e8f0;margin:24px 0;" />`
  );

  return sendMail({
    to: email,
    subject: subjects[language] || subjects.en,
    html: htmlBody,
    text: `Payment confirmed (${amount} ${currency}): ${reference}`,
    attachments
  });
}

async function sendJobAlertEmail({ email, language = 'en', jobs }) {
  if (!jobs || !jobs.length) return { success: true, consoleOnly: true };

  const baseUrl = frontendUrl();
  const isFr = language === 'fr';

  const list = jobs.map((job) => {
    const title = (job.title || 'Job').replace(/</g, '&lt;');
    const company = (job.company || '').replace(/</g, '&lt;');
    const location = (job.location || 'Cameroon').replace(/</g, '&lt;');
    const url = `${baseUrl}/jobs/${job._id}`;
    return `<li style="margin:0 0 10px;padding:10px 12px;background:#f8fafc;border:1px solid #e2e8f0;border-radius:8px;">
      <a href="${url}" style="color:#4f46e5;font-weight:600;text-decoration:none;">${title}</a>
      <p style="margin:2px 0 0;color:#64748b;font-size:13px;">${company} — ${location}</p>
    </li>`;
  }).join('');

  const subjects = {
    en: `${jobs.length} new ${jobs.length > 1 ? 'jobs' : 'job'} match your alerts`,
    fr: `${jobs.length} nouvelle${jobs.length > 1 ? 's' : ''} offre${jobs.length > 1 ? 's' : ''} correspond${jobs.length > 1 ? 'ent' : ''} à vos alertes`
  };

  const bodies = {
    en: `
      <div style="font-family:system-ui,sans-serif;max-width:480px;margin:0 auto;padding:32px;">
        <h2 style="color:#4f46e5;">New jobs for you</h2>
        <p>These new job postings match your saved alerts:</p>
        <ul style="list-style:none;padding:0;margin:16px 0;">${list}</ul>
        <a href="${baseUrl}/jobs" style="display:inline-block;background:#4f46e5;color:#fff;padding:12px 24px;border-radius:8px;text-decoration:none;font-weight:600;margin:8px 0;">Browse all jobs</a>
        <hr style="border:none;border-top:1px solid #e2e8f0;margin:24px 0;" />
        <p style="color:#94a3b8;font-size:12px;">CVBoost — Tailor your CV with AI</p>
      </div>
    `,
    fr: `
      <div style="font-family:system-ui,sans-serif;max-width:480px;margin:0 auto;padding:32px;">
        <h2 style="color:#4f46e5;">De nouvelles offres pour vous</h2>
        <p>Ces nouvelles offres d'emploi correspondent à vos alertes :</p>
        <ul style="list-style:none;padding:0;margin:16px 0;">${list}</ul>
        <a href="${baseUrl}/jobs" style="display:inline-block;background:#4f46e5;color:#fff;padding:12px 24px;border-radius:8px;text-decoration:none;font-weight:600;margin:8px 0;">Voir toutes les offres</a>
        <hr style="border:none;border-top:1px solid #e2e8f0;margin:24px 0;" />
        <p style="color:#94a3b8;font-size:12px;">CVBoost — Adaptez votre CV avec l'IA</p>
      </div>
    `
  };

  return sendMail({
    to: email,
    subject: subjects[language] || subjects.en,
    html: bodies[language] || bodies.en,
    text: `New jobs match your alerts: ${baseUrl}/jobs`
  });
}

/**
 * Report which transport this deploy would use, without building one.
 *
 * A deploy with no mail configuration is silent: `sendMail` finds no
 * transport, logs the message to the console and returns `{ success: true,
 * consoleOnly: true }` — indistinguishable from a real send. That is how an
 * entire broken mail setup can look healthy until someone waits for a
 * verification link. The startup summary needs to be able to say so up front,
 * the same way it already reports `redis=` and `push=`.
 *
 * Presence-only, so it is safe to call at boot and never touches a secret.
 *
 *   'brevo'  — real delivery over HTTPS (the only path Render's free tier allows)
 *   'smtp'   — real delivery over SMTP, which Render free instances block
 *   'console'— no delivery at all; messages are only written to the log
 */
function transportStatus() {
  // Trims before testing: a whitespace-only value is a field that was cleared
  // but not emptied, and it must read as unset here rather than configuring a
  // transport that cannot authenticate.
  const has = (name) => Boolean(String(process.env[name] || '').trim());

  if (has('BREVO_API_KEY')) return 'brevo';
  if (has('SMTP_HOST')) {
    return has('SMTP_USER') && has('SMTP_PASS') ? 'smtp' : 'smtp-no-auth';
  }
  return 'console';
}

/**
 * The daily digest: one email listing everything that matched a saved alert since
 * the last digest, rather than one email per match.
 *
 * Built from the Notification rows the alert matcher already wrote, so the digest
 * cannot drift from what the user sees in-app -- there is no second matching pass
 * that could disagree with the first about what matched.
 *
 * `totalMatched` is the count before `DIGEST_JOB_LIMIT` truncated the list. The
 * difference is stated in the body rather than hidden, because "you have 40
 * matches and the email shows 15" read as a bug otherwise.
 */
async function sendDailyDigestEmail({ email, name, language = 'en', jobs, totalMatched = 0 }) {
  if (!jobs || !jobs.length) return { success: true, consoleOnly: true };

  const baseUrl = frontendUrl();
  const isFr = language === 'fr';

  // htmlText, not escapeHtml: the stored values have already been through the
  // scraper's clean(), and that is not the same as being safe to embed -- it only
  // decodes &nbsp; and leaves every other entity, including markup, in place.
  const list = jobs.map((job) => {
    const title = htmlText(job.title || (isFr ? 'Offre' : 'Job'));
    const company = htmlText(job.company || '');
    const location = htmlText(job.location || (isFr ? 'Cameroun' : 'Cameroon'));
    const url = `${baseUrl}/jobs/${encodeURIComponent(String(job._id))}`;
    // Expired listings stay clickable. The board keeps serving them, marked
    // expired, and a digest that dropped them would silently under-report matches.
    const expired = job.active === false;
    const tag = expired
      ? `<span style="color:#b45309;font-size:11px;">${isFr ? 'b expirée' : 'expired'}</span>`
      : '';
    return `<li style="margin:0 0 10px;padding:10px 12px;background:#f8fafc;border:1px solid #e2e8f0;border-radius:8px;">
      <a href="${url}" style="color:#4f46e5;font-weight:600;text-decoration:none;">${title}</a>
      <p style="margin:2px 0 0;color:#64748b;font-size:13px;">${company} &middot; ${location} ${tag}</p>
    </li>`;
  }).join('');

  const hidden = totalMatched - jobs.length;
  const overflow = hidden > 0
    ? `<p style="color:#94a3b8;font-size:12px;">${isFr
        ? `et ${hidden} autre(s) sur la page.`
        : `and ${hidden} more on the board.`}</p>`
    : '';
  // One phrase, used by both parts. They drifted apart once already, which is how a
  // text-only client ends up reading a different email from an HTML one.
  const overflowText = hidden > 0
    ? (isFr ? `et ${hidden} autre(s) sur la page.` : `and ${hidden} more on the board.`)
    : '';

  const greeting = name ? (isFr ? `Bonjour ${htmlText(name)},` : `Hi ${htmlText(name)},`) : '';
  // Stripped, not escaped: this one lands in the text part, where the reader wants
  // their own name rather than an entity-encoded version of it.
  const greetingPlain = name ? (isFr ? `Bonjour ${plainText(name)},` : `Hi ${plainText(name)},`) : '';
  const count = totalMatched;

  const subjects = {
    en: `${count} job${count > 1 ? 's' : ''} matched your alerts${hidden > 0 ? ` (${jobs.length} shown)` : ''}`,
    fr: `${count} offre${count > 1 ? 's' : ''} correspondent${count > 1 ? 'ent' : ''} à vos alertes${hidden > 0 ? ` (${jobs.length} affichée${jobs.length > 1 ? 's' : ''})` : ''}`
  };

  const bodies = {
    en: `
      <div style="font-family:system-ui,sans-serif;max-width:480px;margin:0 auto;padding:32px;">
        <h2 style="color:#4f46e5;">Your daily job digest</h2>
        ${greeting ? `<p style="color:#334155;">${greeting}</p>` : ''}
        <p style="color:#334155;">${count} new ${count > 1 ? 'listings matched' : 'listing matched'} your saved ${count > 1 ? 'alerts' : 'alert'} since the last digest.</p>
        <ul style="list-style:none;padding:0;margin:16px 0;">${list}</ul>
        ${overflow}
        <a href="${baseUrl}/jobs" style="display:inline-block;background:#4f46e5;color:#fff;padding:12px 24px;border-radius:8px;text-decoration:none;font-weight:600;margin:8px 0;">Browse all jobs</a>
        <hr style="border:none;border-top:1px solid #e2e8f0;margin:24px 0;" />
        <p style="color:#94a3b8;font-size:12px;">CVBoost &mdash; Turn this off in Settings.</p>
      </div>`,
    fr: `
      <div style="font-family:system-ui,sans-serif;max-width:480px;margin:0 auto;padding:32px;">
        <h2 style="color:#4f46e5;">Votre résumé quotidien</h2>
        ${greeting ? `<p style="color:#334155;">${greeting}</p>` : ''}
        <p style="color:#334155;">${count} nouvelle${count > 1 ? 's' : ''} offre${count > 1 ? 's' : ''} correspond${count > 1 ? 'ent' : ''} à vos alertes depuis le dernier résumé.</p>
        <ul style="list-style:none;padding:0;margin:16px 0;">${list}</ul>
        ${overflow}
        <a href="${baseUrl}/jobs" style="display:inline-block;background:#4f46e5;color:#fff;padding:12px 24px;border-radius:8px;text-decoration:none;font-weight:600;margin:8px 0;">Voir toutes les offres</a>
        <hr style="border:none;border-top:1px solid #e2e8f0;margin:24px 0;" />
        <p style="color:#94a3b8;font-size:12px;">CVBoost &mdash; Désactivez ceci dans les paramètres.</p>
      </div>`
  };

  // Every value interpolated into the text part goes through plainText, not escapeHtml.
  // escapeHtml in a text/plain part is the wrong tool: it would leave the reader
  // looking at "&lt;img src=x&gt;" while the tag itself survived in the message.
  const plainJobs = jobs.map((job) => {
    const bits = [
      `- ${plainText(job.title || (isFr ? 'Offre' : 'Job'))}`,
      job.company ? ` (${plainText(job.company)})` : '',
      job.location ? ` - ${plainText(job.location)}` : '',
      job.active === false ? (isFr ? ' [b expirée]' : ' [expired]') : ''
    ].join('');
    return `${bits}\n  ${baseUrl}/jobs/${encodeURIComponent(String(job._id))}`;
  }).join('\n');

  const plainBodies = {
    en: `${greetingPlain}\n\n${count} new listing${count > 1 ? 's' : ''} matched your saved alert${count > 1 ? 's' : ''} since the last digest:\n\n`
      + plainJobs
      + `${overflowText ? `\n\n${overflowText}` : ''}\n\nBrowse all jobs: ${baseUrl}/jobs\n\nTurn this off in Settings.`,
    fr: `${greetingPlain}\n\n${count} nouvelle${count > 1 ? 's' : ''} offre${count > 1 ? 's' : ''} correspond${count > 1 ? 'ent' : ''} à vos alertes :\n\n`
      + plainJobs
      + `${overflowText ? `\n\n${overflowText}` : ''}\n\nVoir toutes les offres : ${baseUrl}/jobs\n\nDésactivez ceci dans les paramètres.`
  };

  return sendMail({
    to: email,
    subject: subjects[isFr ? 'fr' : 'en'],
    html: bodies[isFr ? 'fr' : 'en'],
    text: plainBodies[isFr ? 'fr' : 'en']
  });
}

module.exports = {
  sendMail,
  sendPasswordResetEmail,
  sendVerificationEmail,
  sendPaymentReceiptEmail,
  sendJobAlertEmail,
  sendDailyDigestEmail,
  transportStatus,
  plainText,
  htmlText,
  decodeEntities
};
